version: "3.7"

services:
  postgres:
    container_name: local-postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mygameplanner
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    container_name: local-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
